<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// --- Public Controllers ---
use App\Http\Controllers\HomeController;

// --- Auth Controllers ---
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\ProfileController; // Used by Breeze/Jetstream for generic profile management

// --- User-side Controllers ---
use App\Http\Controllers\User\UserDashboardController;
use App\Http\Controllers\User\UserProfileController;
use App\Http\Controllers\User\UserOrderController;
use App\Http\Controllers\User\AddressController as UserAddressController;
use App\Http\Controllers\User\UserCartController;
use App\Http\Controllers\User\CategoryController as UserCategoryController;
use App\Http\Controllers\User\ProductController as UserProductController;
use App\Http\Controllers\User\UserTablesController;


// --- Admin-side Controllers ---
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\AdminOrderController;
// Corrected: Directly import AdminUserController as it is named in your file system
use App\Http\Controllers\Admin\AdminUserController; // THIS LINE IS CORRECT
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
| REMEMBER TO RUN: php artisan optimize:clear after making route changes.
*/

// --------------------------------------------------------------------------
// Public Routes (Accessible to everyone)
// --------------------------------------------------------------------------
Route::get('/', [HomeController::class, 'index'])->name('home');


// --------------------------------------------------------------------------
// Authentication Routes (Generated by Laravel Breeze/Jetstream if used)
// --------------------------------------------------------------------------
require __DIR__ . '/auth.php'; // Includes routes for login, register, password reset, etc.


// --------------------------------------------------------------------------
// Authenticated User Routes (General - for any logged-in user)
// --------------------------------------------------------------------------
Route::middleware('auth')->group(function () {
    // These routes might be part of your 'user' prefixed group,
    // but if you have generic profile management outside that group,
    // uncomment and use them here.
    // Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    // Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    // Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});


// --------------------------------------------------------------------------
// User Dashboard Specific Routes (Requires 'auth' middleware)
// --------------------------------------------------------------------------
Route::middleware(['auth'])->prefix('user')->name('user.')->group(function () {

    // User Dashboard
    Route::get('/dashboard', [UserDashboardController::class, 'index'])->name('dashboard');

    // User Profile Management
    Route::get('/profile', [UserProfileController::class, 'show'])->name('profile.show');
    Route::get('/profile/edit', [UserProfileController::class, 'show'])->name('profile.edit'); // Often combined or redirects to show for simple profiles
    Route::put('/profile', [UserProfileController::class, 'update'])->name('profile.update');

    // User Orders
    Route::get('/orders', [UserOrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/{order}', [UserOrderController::class, 'show'])->name('orders.show');

    // User Addresses (Using Resource Controller for full CRUD operations, excluding 'show' for a list view)
    Route::resource('addresses', UserAddressController::class)->except(['show']);

    // --- User Cart Routes ---
    Route::get('/cart', [UserCartController::class, 'index'])->name('cart.index');
    Route::post('/cart/add', [UserCartController::class, 'addToCart'])->name('cart.add');
    Route::patch('/cart/update/{cartItem}', [UserCartController::class, 'updateCart'])->name('cart.update');
    Route::delete('/cart/remove/{cartItem}', [UserCartController::class, 'removeFromCart'])->name('cart.remove');
    // --- End User Cart Routes ---

    // Checkout and Order Placement
    Route::get('/checkout', [UserOrderController::class, 'checkoutForm'])->name('checkout.form');
    Route::post('/checkout/place-order', [UserOrderController::class, 'placeOrder'])->name('checkout.place_order');
    Route::get('/order-confirmation/{order}', [UserOrderController::class, 'confirmation'])->name('order.confirmation');

    // Dynamic Category and Product Display for User Interface
    Route::get('/category/{category:slug}', [UserCategoryController::class, 'showProductsByCategory'])->name('category.products');
    Route::get('/products', [UserProductController::class, 'index'])->name('products.index'); // Generic Product Browsing
    Route::get('/products/{product}', [UserProductController::class, 'show'])->name('products.show'); // Product Detail Page
    Route::post('/products/add-to-cart', [UserProductController::class, 'addToCart'])->name('products.add-to-cart'); // Add to cart from product page

    // --- User Tables Route (if applicable) ---
    Route::get('/tables', [UserTablesController::class, 'index'])->name('tables');
    // --- End User Tables Route ---

});


// --------------------------------------------------------------------------
// Admin Dashboard Routes (Requires 'auth' and 'is_admin' middleware)
// --------------------------------------------------------------------------
Route::middleware(['auth', 'is_admin'])->prefix('admin')->name('admin.')->group(function () {

    // Admin Dashboard
    Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');

    // Product Management (Explicit routes for granular control)
    Route::get('/products', [AdminProductController::class, 'index'])->name('products.index');
    Route::get('/products/create', [AdminProductController::class, 'create'])->name('products.create');
    Route::post('/products', [AdminProductController::class, 'store'])->name('products.store');
    Route::get('/products/{product}/edit', [AdminProductController::class, 'edit'])->name('products.edit');
    Route::patch('/products/{product}', [AdminProductController::class, 'update'])->name('products.update');
    Route::delete('/products/{product}', [AdminProductController::class, 'destroy'])->name('products.destroy');

    // Category Management (Full CRUD using a Resource Controller)
    Route::resource('categories', AdminCategoryController::class);

    // Admin Order Management
    Route::get('/orders', [AdminOrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/{order}', [AdminOrderController::class, 'show'])->name('orders.show');
    // Route for updating order status - This is the corrected route name as per your web.php
    Route::patch('/orders/{order}/status', [AdminOrderController::class, 'updateStatus'])->name('orders.update_status');

    // USER MANAGEMENT
    // THIS IS THE LINE THAT NEEDS TO BE CHANGED:
    // Old: Route::get('/users', [AdminUserController::class, 'index'])->name('users.index');
    // New: Use Route::resource to define all CRUD routes for 'users'.
    // This will define 'admin.users.index', 'admin.users.destroy', 'admin.users.edit', etc.
    Route::resource('users', AdminUserController::class); // <-- CORRECTED LINE
});


// --------------------------------------------------------------------------
// Logout Route (Common for both user and admin)
// --------------------------------------------------------------------------
Route::post('/logout', function () {
    Auth::logout();
    session()->invalidate();
    session()->regenerateToken();
    return redirect('/login'); // Redirect to your login page after logout
})->name('logout');